<MyLayout>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        padding: 30 # Снаружи элементов
        spacing: 20 # Внутри между элементами

        Button:
            text: "Hello"
        Button:
            text: "Bye"
        Button:
            text: "Hungry"
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            size_hint: (0.5, 0.5)
            # width: 100
            # height: 50
